deployment:
  image:
    pullPolicy: IfNotPresent

  securityContext: # Set on container level
    runAsUser: 2000
    allowPrivilegeEscalation: false

security:
  skipTLSCertificateVeryfication: false

gardener:
  auditLogsPolicyConfigMap: ""

provisioner: "gardener"

kymaRelease:
  preReleases:
    enabled: true
  onDemand:
    enabled: true

installation:
  timeout: 50m
  errorsCountFailureThreshold: 5

tests:
  enabled: false
  gcp:
    credentials: ""
    projectName: ""
  gardener:
    providers: "Azure"
    azureSecret: "" # Name of Gardener secret for Azure
    gcpSecret: "" # Name of Gardener secret for GCP
  kyma:
    version: "1.10.0"
  queryLogging: false
